package com.agile.ecloud.sdk.bean;

import java.util.Date;

public class Account {

    private  String signPwd;

    public String getSignPwd() {
        return signPwd;
    }

    public void setSignPwd(String signPwd) {
        this.signPwd = signPwd;
    }

    private String photoPath;

    public String getPhotoPath() {
        return photoPath;
    }

    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_id
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private Integer accId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.mobile
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_type
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private Byte accType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.status
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.real_name
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.person_auth
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private Byte personAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ent_auth
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private Byte entAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email_auth
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private Byte emailAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.mobile_auth
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private Byte mobileAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ctime
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private Date ctime;
    private  Date authTime;

    public Date getAuthTime() {
        return authTime;
    }

    public void setAuthTime(Date authTime) {
        this.authTime = authTime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.audit_result
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private String auditResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.source_name
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private String sourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.source_id
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private Integer sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.source_manager
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private String sourceManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.card_type
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private Byte cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id_card_num
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    private String idCardNum;

    private String realMobile;// 用户真实手机号（虚拟标识需求） 2019.01.14增

    public String getRealMobile() {
        return realMobile;
    }

    public void setRealMobile(String realMobile) {
        this.realMobile = realMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_id
     *
     * @return the value of account.acc_id
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public Integer getAccId() {
        return accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_id
     *
     * @param accId the value for account.acc_id
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setAccId(Integer accId) {
        this.accId = accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.mobile
     *
     * @return the value of account.mobile
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.mobile
     *
     * @param mobile the value for account.mobile
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_type
     *
     * @return the value of account.acc_type
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public Byte getAccType() {
        return accType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_type
     *
     * @param accType the value for account.acc_type
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setAccType(Byte accType) {
        this.accType = accType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.status
     *
     * @return the value of account.status
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.status
     *
     * @param status the value for account.status
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.real_name
     *
     * @return the value of account.real_name
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public Object getRealName() {
            return realName == null ? "" : realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.real_name
     *
     * @param realName the value for account.real_name
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.person_auth
     *
     * @return the value of account.person_auth
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public Byte getPersonAuth() {
        return personAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.person_auth
     *
     * @param personAuth the value for account.person_auth
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setPersonAuth(Byte personAuth) {
        this.personAuth = personAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.ent_auth
     *
     * @return the value of account.ent_auth
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public Byte getEntAuth() {
        return entAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.ent_auth
     *
     * @param entAuth the value for account.ent_auth
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setEntAuth(Byte entAuth) {
        this.entAuth = entAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.email_auth
     *
     * @return the value of account.email_auth
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public Byte getEmailAuth() {
        return emailAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.email_auth
     *
     * @param emailAuth the value for account.email_auth
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setEmailAuth(Byte emailAuth) {
        this.emailAuth = emailAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.mobile_auth
     *
     * @return the value of account.mobile_auth
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public Byte getMobileAuth() {
        return mobileAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.mobile_auth
     *
     * @param mobileAuth the value for account.mobile_auth
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setMobileAuth(Byte mobileAuth) {
        this.mobileAuth = mobileAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.ctime
     *
     * @return the value of account.ctime
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.ctime
     *
     * @param ctime the value for account.ctime
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.audit_result
     *
     * @return the value of account.audit_result
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public String getAuditResult() {
        return auditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.audit_result
     *
     * @param auditResult the value for account.audit_result
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setAuditResult(String auditResult) {
        this.auditResult = auditResult == null ? null : auditResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.source_name
     *
     * @return the value of account.source_name
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.source_name
     *
     * @param sourceName the value for account.source_name
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.source_id
     *
     * @return the value of account.source_id
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.source_id
     *
     * @param sourceId the value for account.source_id
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.source_manager
     *
     * @return the value of account.source_manager
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public String getSourceManager() {
        return sourceManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.source_manager
     *
     * @param sourceManager the value for account.source_manager
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setSourceManager(String sourceManager) {
        this.sourceManager = sourceManager == null ? null : sourceManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.card_type
     *
     * @return the value of account.card_type
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public Byte getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.card_type
     *
     * @param cardType the value for account.card_type
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setCardType(Byte cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id_card_num
     *
     * @return the value of account.id_card_num
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public String getIdCardNum() {
        return idCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id_card_num
     *
     * @param idCardNum the value for account.id_card_num
     *
     * @mbggenerated Mon Nov 07 09:53:56 CST 2016
     */
    public void setIdCardNum(String idCardNum) {
        this.idCardNum = idCardNum == null ? null : idCardNum.trim();
    }
}